version: "3.8"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"

  laravel-api:
    build:
      context: ./networking/apiRestLavarel
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_URL: ${APP_URL}
      APP_DEBUG: ${APP_DEBUG}
      APP_ENV: ${APP_ENV}
      APP_NAME: ${APP_NAME}
    depends_on:
      - db

  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      SESSION_SECRET: ${SESSION_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_URL: ${REDIS_URL} # <-- Añadir esto aquí
    depends_on:
      - db
      - redis

  validator:
    build:
      context: ./services/validator
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  frontend:
    build:
      context: ./webapps/calendarWeb
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - laravel-api
      - auth-service
      - validator

  init-admin:
    image: curlimages/curl:7.85.0
    depends_on:
      - laravel-api
    entrypoint:
      [
        "/bin/sh",
        "-c",
        'sleep 20 && curl -X POST http://laravel-api/auth/register -H ''Content-Type: application/json'' -d ''{"username": "admin", "password": "admin", "email": "admin@admin.com", "role": "admin"}''',
      ]

volumes:
  db_data:
